### ISSUE TITLE
Discord API & client mention string inconsistency

### ISSUE THREAD

**Issue by rajenr** [Headline/Steam-Discord-Bot#18]
Allows mention of user, such as below.
![screenshot_20180322-012952 2](https://user-images.githubusercontent.com/32354550/37759367-9cc9c498-2d70-11e8-8646-f594d4cef4d0.png)

**Comment by Headline** [comment]
This is really annoying. After brainstorming it appears that the `Mention` string discord API supplies us isn’t always equal to mentions on the clients themselves. We’ll probably have to resolve the mentioned username ourself, which is annoying

**Comment by Headline** [comment]
If anyone beats me to it, here’s the bad comparison 
https://github.com/Headline/Steam-Discord-Bot/blob/35c71bf1b4f71ea09a61758d6ad7d75dd992c568/Commands/Facts.cs#L25

**Comment by Headline** [comment]
Discord mentions work by putting the user's userid into the form of `<@XXXXX>` where `XXXXX` is the userid. We'll just check the to see if the sender's Id exists in the string.
